### ISSUE TITLE
Light use efficiency

### ISSUE THREAD

**Issue by kongdd** [zhangyaonju/Global_GPP_VPM_NCEP_C3C4#1]
Hi Yao, 

The parameter of `LUTepsilon` in the [script](https://github.com/zhangyaonju/Global_GPP_VPM_NCEP_C3C4/blob/c09bc58a7a0bd066ef4f3c78bb836193deb4a53c/GPP_C6_for_cattle.py#L145) is different from your paper (Zhang, 2017, Scientific data, Table2). 
Is that correct? Which one can I use?

Cheers,
Dongdong

**Comment by zhangyaonju** [comment]
Hi Dongdong, 

This is a unit conversion problem, in the paper the radiation unit is mol PAR, in the code, we directly used the W/m2, 
0.42 g C m-2 day-1/mol m-2 day -1
             =0.078 g C m-2 day -1 /W m-2 

Let me know if it is clear or not.

Yao

**Comment by kongdd** [comment]
Yeah, it's clear. Thank you!
