### ISSUE TITLE
questions about PAR equation

### ISSUE THREAD

**Issue by kongdd** [zhangyaonju/Global_GPP_VPM_NCEP_C3C4#2]
Hi Yao, 

There are some misleading about `PAR` equation. 
Generally, `PAR = 0.45*Rs` (e.g. in MODIS MOD17C6). But in your script, it seems that `PAR=Rs` directly. Is the following parameter calibration (e.g. ε0) also based on `PAR=Rs`?

Taking `PAR=Rs`, in my tries, the overall NSE is about 0.53.  When using the GPP_vpm you gave to me, the NSE is about 0.71. My result is far inferior to yours. Currently, I used the meteorological forcing from the flux sites and didn't smooth EVI, which might contribute to the lower performance slightly. 
Did you calibrate VPM's parameter on the site scale?

Thanks for your help!
Dongdong

**Comment by zhangyaonju** [comment]
Hi Dongdong,

Thank you for you interest and raising this question.
I just checked the code. There should be no problem. Basically, we put the PAR calculation in the LUE.
1 W m-2 (Shortwave Radiation, SR)= 4.55 * 10-6 mol m-2 s-1 (SR) = 0.48 * 4.55 * 10-6 mol m -2 s-1 (PAR) = 2.148 * 10-6 mol m-2 s-1 (PAR) = 0.186 mol m-2 day -1 (PAR) 
If the LUE is 0.42 g C/ mol PAR, then it also equals to 0.07812 g C day-1 W-1  shortwave. In the code, you will find that the LUE values are 0.078 not 0.42 as suggested in the paper.

Let me know if this makes sense.

Best,
Yao

**Comment by kongdd** [comment]
Thanks for your quick reply. I didn't realize that it's the problem of unit.
But, I don't understand where is the 0.48 from. Could you give a document or reference about this?

Cheers

**Comment by zhangyaonju** [comment]
Hi,

The 0.48 converts shortwave radiation to PAR. I cannot find the original document that provide this number, but after a quick search, I think this value has a range between 0.42 to 0.52, and one study suggest 0.473. Do you have other numbers for this?

https://link.springer.com/article/10.1007/BF00864910 <https://link.springer.com/article/10.1007/BF00864910>

Best,
Yao

**Comment by kongdd** [comment]
Got it! Thanks very much

**Comment by kongdd** [comment]
Hi Yao, 

Another question:
When calibrating parameters, which meteorological forcing (e.g. Rs and T) are you using?  From flux sites or from NCEP Reanalysis II?

After smoothing EVI, NSE increases to 0.62, which is still inferior to yours (about 0.71). Any suggestion? Currently, the difference between C3 and C4 is not taken into consideration. Is this matter?

Regards,
Dongdong

**Comment by zhangyaonju** [comment]
Hi Dongdong,

Actually we did not do much parameter calibration. The parameters are mostly based on previous site level studies (for LUEmax) and from literature (for temperature related parameters). 
Please remind me how you get the NSE? Are you running the VPM for all flux tower sites? Did you use all site years? The C3 and C4 difference definitely affect this result. But I’m not sure  to what extent.

Best,
Yao

**Comment by kongdd** [comment]
I realized that I should use daytime temperature, other than daily temperature. But I can't understand how do you generate daytime temperature from NCEP Tmin and Tmax in `climate_data_ncep_aggregate`. 

Is `T_daytime = Tmin*0.25 + Tmax*0.75`?

**Comment by zhangyaonju** [comment]
Hi Dongdong,

Yes, the daytime temperature is the mean of maximum and mean temperature, your equation is correct.

Best,
Yao

**Comment by kongdd** [comment]
Thank you!
